name: azuixin
on: push
jobs:
  algolia:
    runs-on: ubuntu-latest
    container: node:16.16.0 
    steps:
      - uses: actions/checkout@v3
      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo "config=$(cat crawlerConfig.json | jq -r tostring)" >> $GITHUB_OUTPUT
      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: 5ZS6VKQ2HV
          API_KEY: 110a86d378c2682ea2f1ccfdceb9f0d3
          CONFIG: ${{ steps.algolia_config.outputs.config }}
